### ISSUE TITLE
zigbee-moisture-sensor-v2 - need to change timing for heartbeat

### ISSUE THREAD

**Issue by briankitt** [Mariano-Github/Edge-Drivers-Beta#116]
I'm using zigbee-moisture-sensor-v2 with this sensor:
https://www.amazon.com/dp/B0CLJ951YS

It works perfectly, well, almost.

The water sensor doesn't appear to broadcast often enough to satisfy the drivers minimum broadcast requirements.

All day long, the sensors go offline, then online, then offline, then online, etc.

It's done cyclic, so that indicates to me that the water sensors are working, just not 'often enough'.

Is there a way to tweak the driver to increase the timeout before it decides it's 'offline'?

I have 18 sensors, and get notified constantly all day (and all night) that they are going online and offline.

**Comment by Mariano-Github** [comment]
The driver configures the device with the default smartthings values:

300 sec for cluster 500, attribute 0002
 
21609 sec for battery, cluster 0001

The hub marks as offline when no message is received from those clusters for approximately 2:30 hours.

If it appears offline intermittently, it means that one of the clusters has not been configured correctly in the installation and does not send periodic messages or the messages do not reach the hub due to poor quality or signal strength.

These devices are usually placed in inaccessible places, under metal appliances, which attenuate the 2.4 GHz zigbee signal.

Try reinstalling the devices near the hub and placing repeaters, plugs, etc. for those that are further away from the hub.

You can use zwave sensors, which have lower frequencies, 800 MHz, and have less noise and have a longer range.

There are some tuya TS0207 models, which do not configure cluster 500 correctly and disconnect and reconnect when they receive the battery message, cluster 0001, which report every 6 hours

**Comment by briankitt** [comment]
It's not a communication issue, I can guarantee that.
#1) I drop them in water, they immediately become 'active' in smart things,
and report wet.
#2) I set 1/2 dozen around the hub (within inches) and they still cycled
offline/online/offline/online all day and night.
#3) They cycle at regular intervals that you could set your clock to.   To
me, it looks like they are reporting every 4 hours on the nose.  It's very
regular.

Is there any way I can change the driver or some setting to wait 5 hours
before reporting it as 'offline'?

That's all I need to do to fix it.

**Comment by Mariano-Github** [comment]
The time to display offline is strictly controlled by the hub, not by the driver.

The 4 hours interval fits with what I told you, it is offline after about 2.30 hours, 4 hours later the battery message arrives to hub and it goes online for another 2.30 hours and 4 hours later another battery message arrives again ...

It is a problem with some Tuya TS0207 models, they do not send periodic 300 sec reports from cluster 500.

I could to configure battery reports every 1 hour instead of 6 hours, if can identify with model and manufacturer, which tuya devices have the problem, but if I do it to all of devices indiscriminately it would mean excessive and unnecessary battery consumption on the devices that work correctly.

**Comment by briankitt** [comment]
What about giving us an option, where we can set that interval?   We could
go into settings, and set it on a device by device basis.

Here are screen prints of what I see:
[image: image.png]

[image: image.png]
[image: image.png]
[image: image.png]
[image: image.png]

**Comment by briankitt** [comment]
Did you not get my prior response?
I sent the make, manufacturer, and screen prints from ST?
https://www.amazon.com/dp/B0CLJ951YS

**Comment by Mariano-Github** [comment]
I can not see the puctures posted

**Comment by briankitt** [comment]
![image](https://github.com/Mariano-Github/Edge-Drivers-Beta/assets/3027960/0dd1824b-b37e-4a9e-b815-c5c8fa30f6eb)
![image](https://github.com/Mariano-Github/Edge-Drivers-Beta/assets/3027960/610ff134-a32e-4a30-8be5-0d88851b8d05)
![image](https://github.com/Mariano-Github/Edge-Drivers-Beta/assets/3027960/9717768e-53a8-425c-82fb-987ade3363da)
![image](https://github.com/Mariano-Github/Edge-Drivers-Beta/assets/3027960/f821e76b-420c-48d1-91e2-a9f780ae91c5)


And then the device is here on Amazon
https://www.amazon.com/dp/B0CLJ951YS

**Comment by Mariano-Github** [comment]
Modified configuration for battery report interval 3600 sec.

To device configure with new values you need instal or reinstall devices.

To reinstall devices without uninstall it:
- Install this driver version or wait to driver updated automatically
- Put device in pairing mode
- In app, add device with search nearby option
- Device will re install and configured with lost any routine or scenes

```
───────────────────────────────────────────────────
 Name         Zigbee Moisture Sensor Mc
 Version      2024-04-19T20:08:04.635029836
───────────────────────────────────────────────────
```

**Comment by briankitt** [comment]
Well bummer.
I uploaded the new driver to my SmartThings
I deleted every water sensor I have (18 of them)
I then paired all 18 back.
I then verified that they were all using the new 2024-04-19 driver, which
they all did automatically.
Within 2 hours they were going offline due to no response.

**Comment by briankitt** [comment]
What's next?   They are still cycling offline and online?

**Comment by Mariano-Github** [comment]
I have no idea what is happening to your devices.

These devices are cheap and work well with your platform, but on other platforms they can be a pain.

If you send me the logs with the device pairing CLI and I can see what messages the device sends when it is configured, then I could analyze what happens, but I can't guarantee anything with these devices.

**Comment by briankitt** [comment]
I don't know where these logs are, I looked for them, but can't find them.
Can you point me in the right direction?
Thanks

**Comment by Mariano-Github** [comment]
This is a tutorial to install cli in windows and capture logs


https://community.smartthings.com/t/edge-driver-or-device-handeler-for-a-tuya-zemismart-zigbee-plug-with-energy-mesurment-capabilities/245383/18

**Comment by briankitt** [comment]
This is VERY informative, and I've learned an incredible amount about my devices.
1 thing, for example, is that devices are reporting far more frequently then I guessed.  
I apologize, I should have done this first, this would have given you so much more information about my problem.

First off, check out this screen print.  Look at the devices that are offline.   I intentionally captured my time, so you could compare my time (Central Daylight Time) to the Smart Things debug log time stamps.

![image](https://github.com/Mariano-Github/Edge-Drivers-Beta/assets/3027960/082f075c-c62a-4f4b-b526-052e6d145029)


Now, look at the log.  Even though these devices are showing 'offline', they are reporting on a regular basis?
So how does that happen?  They are successfully reporting, yet, SmartThings shows they are offline?
That seems odd.
But clearly,  the problem is not in the reporting of the status?

Here is 1 hour worth of log.  Let me know if you need more.
[Zigbee.log](https://github.com/Mariano-Github/Edge-Drivers-Beta/files/15182779/Zigbee.log)

**Comment by Mariano-Github** [comment]
I have looked at the entire log, taking note of the most relevant of the 18 sensors:
- starts at 18:17:10 and ends at 01:31:11
- At 18:37:52 "Washing Maching" sensor was removed
- At 18:55:12 It is reinstalled and configured.
- Battery configuration 3600 sec. Device response: Ok
- IASzone configuration, cluster 0500 (dry or wey) 2100 sec. Device response: Ok
- The battery and IASZone attributes are read and the capabilities are initialized with the values received: 93% and Dry.
- Only one sensor (Master small sink), during the log, spontaneously reports cluster 0500, (dry) only once at 00:31:11.
- No other sensor spontaneously reports either cluster 0500, (dry or wet) or cluster 0001, (Batt).

- All the logs you see are the activation of the Health Check function to read cluster 0500, attribute 0002, because the messages are not received.
- the device does not respond to readings because it is asleep.
- Result, they are all offline except the "Master small Sink" when the report was received at 00:31:11.

The problem is not very clear:
- The device responds that it accepts the configuration, but no periodic reports are received from the device, neither battery nor IASZone.
- When a spontaneous reporter message is received from a device, the Rssi intensity: -86 dbm is quite low.
- It could be that the messages are issued and do not reach the Hub, although it is strange that almost none arrive.
- It could be that the devices do not send messages correctly, but it is rare for them all to fail.
- You could try placing two sensors near the hub to see if they stay online and send periodic reports.
- I can't think of anything else to try.

I attach a photo of the summary of the logs
![PXL_20240501_170240915](https://github.com/Mariano-Github/Edge-Drivers-Beta/assets/74271621/40d408ef-8d9d-4787-a319-2285ccd7cff6)

**Comment by briankitt** [comment]
I intentionally excluded that one, and then re-included it, for purposes of
logging.

Would more logging help?   The one that says 'laundry water inlet' is less
than 5 feet from the hub?   If that's too far, the hub has a problem.  And
that one is currently offline.

I could do a whole day of logging if you want.

**Comment by Mariano-Github** [comment]
What channel do you have the router's WiFi on and what zigbee channel does the hub have?
they could be interfering

**Comment by briankitt** [comment]
I have a number of electronic devices, kind of all together.
I have a Netgear ORBI 2.4 GHZ at 11, 5 GHZ at 40
I have a Century link router, that broadcasts 2.4 GHZ at 1, and t GHZ at 161
I have an AccuRite weather station that is broadcasting, but I don't know
the channel it uses.  I'm researching, I just don't have time to research
now as I am at work.
I have an X-Sense smoke alarm, but don't know how to find the channel it
uses.  I'm researching
I have 3 Google Nest Displays, but 99% sure, they only use WiFi, no
additional radio.
I have a SmartThings hub, but I need to find out what channel it uses.  I
just don't know where to look, I'm researching.

**Comment by briankitt** [comment]
It appears the zigbee channel is not changeable and cannot be displayed, at
least, that's what I'm finding?

**Comment by Mariano-Github** [comment]
Zigbee channel can see and change in my.smartthings.com advanced users

![Screenshot_20240502-200641](https://github.com/Mariano-Github/Edge-Drivers-Beta/assets/74271621/f5dcaec4-6497-4d40-98d0-ef5ee9bccb63)

Wifi 2.4 ghz channel can see and change in your router settings

**Comment by Mariano-Github** [comment]
This is a publish of interference zigbee and wifi channels

https://www.metageek.com/training/resources/zigbee-wifi-coexistence.html

**Comment by briankitt** [comment]
Oh, got it. sorry.  Per your suggestion, I changed it to 25.   I'll update you after 24 hours, that should be enough time for everything to adjust

![image](https://github.com/Mariano-Github/Edge-Drivers-Beta/assets/3027960/dffa05b7-3fab-469c-b811-e8a769b27d4f)

**Comment by Mariano-Github** [comment]
Some olders devices can have problems with channel 25, but new devices i think work fine

**Comment by briankitt** [comment]
Over the last few days, I've tried a number of channels.   Each time, I
remove and re-add all 18 devices.  Each time, they all go offline within a
few hours.

Any ideas of next steps?   I know you have put forth a great effort to try
to understand what is going on.    I hate to get rid of these.  But I
really want water sensors to watch for leaks.

**Comment by Mariano-Github** [comment]
I don't understand anything, but everything indicates that this device is not working well.

Try a different zigbee detector to see if it is a problem with your zigbee network or not.

These are more expensive, but they do work well.

https://www.google.com/url?sa=t&source=web&rct=j&opi=89978449&url=https://www.amazon.com/-/es/Aeotec-SmartThings-alimentado-concentrador-inteligente/dp/B095TR9NYR&ved=2ahUKEwjNtuXhr_mFAxWExgIHHZkfBpwQFnoECBIQAQ&usg=AOvVaw0hwjdbyhc9pUR01NGk_dLK

**Comment by briankitt** [comment]
Wow, 18 at nearly 40$ a crack, we are looking at a purchase of around 700$

What do other people use for the one I have?  It seems unusual that they
would sell leak detectors, that don't work, and yet still have 4 star
review average?

Is there another hub that works with Smart Things/Google Home that maybe
would give me a better Zigbee compatibility?

**Comment by Mariano-Github** [comment]
I meant buying 1 to test and see if it is a problem with the zigbee network or the devices.

Then you return it and with the conclusions you draw you make a decision.

There may be more models, you can ask in the community, but the TS0207 cause many problems to many users

**Comment by briankitt** [comment]
Thanks!  Go ahead and close this ticket, we beat this one to death.
I can't thank you enough for all of your hard work and advice on this.
