### ISSUE TITLE
Please add zemismart TB26-3 light switch driver

### ISSUE THREAD

**Issue by zemismart** [Mariano-Github/Edge-Drivers-Beta#32]
Hi dear,
How are you?
This is Sky from zemismart.com
Would u like to help us to write edge driver?
We will provide free samples.
Best regards,
Sky

**Comment by Mariano-Github** [comment]
Hi Sky

Hello,

In order to add a device to a edge driver, it is necessary to know the fingerprints, that is, the manufacturer, model and the clusters (capabilities) that it supports.
The brand model does not work.

I don't know exactly what you need, create a driver or add to an existing driver?

currently the number of drives that can be installed in a hub is limited to 50 and therefore it is best to group several devices in each driver.

Regards

**Comment by zemismart** [comment]
Hi Mariano,
Thanks for your reply~
I want to create driver to our devices.
I will provide you the fingerprints information.
Do u need items in your hand too?
Best regards,
Sky

**Comment by zemismart** [comment]
My email is marketing@zemismart.com

**Comment by Mariano-Github** [comment]
Hi Alberto,
Added to this driver version
`───────────────────────────────────────────────────
 Driver Id    bb1b3fd4-dcba-4d55-8d85-58ed7f1979fb 
 Name         Zigbee Light Multifunction Mc        
 Version      2023-01-06T15:55:17.423771514
───────────────────────────────────────────────────
- id: "_TZ3210_e020aaa/TS0505B"
    deviceLabel: RGBW TS0505B
    manufacturer: _TZ3210_e020aaa
    model: TS0505B
    deviceProfileName: rgbw-level-colortemp-2700-6500
`

**Comment by albertovm** [comment]
Thanks... let me try it.

**Comment by albertovm** [comment]
> Thanks... let me try it.

Working fine.

**Comment by albertovm** [comment]
Mariano... the device is not yet recognized. I have no idea what could be happening.
