### ISSUE TITLE
Add Fingerprint ZTS-EUB (MoesGo new identifier)

### ISSUE THREAD

**Issue by gigatux** [Mariano-Github/Edge-Drivers-Beta#67]
Hello,

I just purchased a MoesGo ZigBee Smart Switch - 3 gang. I already have two of these devices, with model number ZS-EUB (ID _TZ3000_qewo8dlz) but the new one appears to be ZTS-EUB and has a identifier _TZE200_tz32mtza .

If it is likely it will work with this driver, can you please add the following fingerprint:

```
  - id: "Moes/_TZE200_tz32mtza"
    deviceLabel: Moes TZE200 Switch
    manufacturer: _TZE200_tz32mtza
    model: TZE200
    deviceProfileName: three-switch
```

I will then happily test and let you know if all works as expected. Thank you.

Marc

**Comment by gigatux** [comment]
FYI, running the devices command with the SmartThings CLI, it says the deviceModel is TS0601, and the one that previously worked was deviceModel TS0013. I'm not sure what one you'd like to list in the fingerprints.

**Comment by Mariano-Github** [comment]
Hi Marc,
If it is the TS0601 model, surely it uses the TUYA cluster EF00 and it does not work with this driver.

Since you use the CLI you can see in the pairing which clusters it uses

There is a thread in the community for the devices that use the EF00 cluster.
https://community.smartthings.com/t/st-edge-personal-tuya-devices-generic-ef00-device/255270

**Comment by gigatux** [comment]
Thank you so much for that.

I'm only now learning about clusters. I'm really surprised MoesGo totally changed how it operates, but I agree it's now EF00 and indeed this is now detected with the Personal Tuya devices driver, albeit as a generic EF00 device at the moment.
